-- ============================================================
-- Script: 02_indices.sql
-- Usuario: admin_optimizacion / Optimizacion123
-- Base de datos: XEPDB1
-- ============================================================

-- Indices B-tree
CREATE INDEX IDX_RESERVAS_PACIENTE ON SUPERADMIN.RESERVAS(id_paciente);
CREATE INDEX IDX_RESERVAS_MEDICO ON SUPERADMIN.RESERVAS(id_medico);
CREATE INDEX IDX_RESERVAS_QUIROFANO ON SUPERADMIN.RESERVAS(id_quirofano);
CREATE INDEX IDX_RESERVAS_FECHA ON SUPERADMIN.RESERVAS(fecha_reserva);
CREATE INDEX IDX_RESERVAS_ESTADO ON SUPERADMIN.RESERVAS(estado);
CREATE INDEX IDX_MEDICOS_ESPECIALIDAD ON SUPERADMIN.MEDICOS(id_especialidad);
CREATE INDEX IDX_MEDICOS_ACTIVO ON SUPERADMIN.MEDICOS(activo);
CREATE INDEX IDX_PACIENTES_EMAIL ON SUPERADMIN.PACIENTES(email);
CREATE INDEX IDX_EMERGENCIAS_PRIORIDAD ON SUPERADMIN.EMERGENCIAS(nivel_prioridad);
CREATE INDEX IDX_USUARIOS_USERNAME ON SUPERADMIN.USUARIOS_SISTEMA(username);
CREATE INDEX IDX_USUARIOS_PERFIL ON SUPERADMIN.USUARIOS_SISTEMA(id_perfil);

-- Indices funcionales
CREATE INDEX IDX_MEDICOS_NOMBRE_UPPER
  ON SUPERADMIN.MEDICOS(UPPER(nombre));
CREATE INDEX IDX_PACIENTES_NOMBRE_UPPER
  ON SUPERADMIN.PACIENTES(UPPER(nombre));
CREATE INDEX IDX_RESERVAS_HORA
  ON SUPERADMIN.RESERVAS(TO_CHAR(hora_inicio, 'HH24'));
CREATE INDEX IDX_ESPECIALIDADES_NOMBRE_UPPER
  ON SUPERADMIN.ESPECIALIDADES(UPPER(nombre));

-- Recolectar estadisticas
BEGIN
  DBMS_STATS.GATHER_SCHEMA_STATS(
    ownname => 'SUPERADMIN',
    cascade => TRUE,
    options => 'GATHER'
  );
END;
/

COMMIT;
